FROM node:17-slim
ARG ROOT_PASS=ROOT
RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
WORKDIR  /utkusarioglu/projects/nextjs-grpc/api
COPY api /utkusarioglu/projects/nextjs-grpc/api
COPY proto /utkusarioglu/projects/nextjs-grpc/proto
WORKDIR /utkusarioglu/projects/nextjs-grpc/api
RUN yarn next build
USER node
ENTRYPOINT yarn start
