FROM node:19-slim
ARG ROOT_PASS=ROOT
RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'
RUN apt update && apt install -y vim curl sudo
WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/api
COPY api /utkusarioglu-com/projects/nextjs-grpc/api
COPY proto /utkusarioglu-com/projects/nextjs-grpc/proto
WORKDIR /utkusarioglu-com/projects/nextjs-grpc/api
RUN yarn build
RUN chown -R 10001:10001 /utkusarioglu-com
USER node
ENTRYPOINT scripts/entrypoint.sh
